ALTER TABLE tenants
    ADD COLUMN IF NOT EXISTS logo_url TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS logo_object_key TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS logo_content_type TEXT NOT NULL DEFAULT '';
